version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: underscore
    versions:
    - 1.12.0
    - 1.12.1
    - 1.13.0
  - dependency-name: socket.io
    versions:
    - 3.1.0
    - 3.1.1
    - 3.1.2
    - 4.0.0
  - dependency-name: mustache
    versions:
    - 4.1.0
  - dependency-name: grunt-contrib-uglify
    versions:
    - 5.0.0
  - dependency-name: grunt-contrib-cssmin
    versions:
    - 3.0.0
